--- #YAML:1.0
name:                Rose-HTMLx-Form-Field-PopUpMenuNumeric
version:             0.001
abstract:            popup menu for numeric values
license:             perl
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Rose::HTML::Objects:           0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
